# Descripcion de los parametros / Parameter Descriptions:
# =========================================================
# [Nombre del Driver] / [Driver Name]
#
# com_method = Hardware de programacion (Actualmente serial o pickit5, para otro nuevo es necesario modificar la libreria omni_driver.py)
#            / Programming hardware (Currently serial or pickit5. To add a new one, omni_driver.py must be modified)
#
# SQTP_method = inject / file (Para otro nuevo es necesario modificar la libreria omni_firmware.py)
#             / inject / file (To add a new one, omni_firmware.py must be modified)
#
# path = ruta del ejecutable (debe ser del tipo linea de comandos)
#      / Path to the executable (must be a CLI / command-line tool)
#
# micros = Microcontroladores aceptados para este driver
#        / Microcontrollers supported by this driver
#
# linea_comando = Aqui la construccion de la linea de comando, usando los comodines a continuacion mostrados
#               / Command line construction, using the placeholders shown below
#
# returncode_ok = el numero que devuelve el programa cuando todo va bien o un texto inequivoco. (El texto debe ser en mayusculas)
#               / The number returned by the program on success, or an unambiguous string. (The text must be in UPPERCASE)
#
# returncode_bad = el numero que devuelve el programa cuando falla la programacion o un texto inequivoco. (forzar algun error para obtener un codigo o texto)
#                / The number returned by the program on failure, or an unambiguous string. (Force an error to get the code or text)

# Para añadir otro metodo de programación aqui aparece la descripcion de las variables.
# Variable descriptions for adding another programming method:
# ----------------------------------------------------------------------
# %path          (ruta del programa / program path)
# %device        (micro que aparecera en el archivo pg / microcontroller that will appear in the pg file)
# %params        (datos que aparecera en el archivo pg / data that will appear in the pg file)
# %port          (puerto que se elige en el GUI, nombre completo / port selected in the GUI, full name)
# %portn         (puerto que se elige en el GUI, solo numero / port selected in the GUI, number only)
# %hex           (ruta del hex que aparece en el archivo pg, o del result.hex que se genera cuando se usa la funcion SQTP, metodo = inject)
#                / path to the hex file in the pg file, or the result.hex generated when using the SQTP function, method = inject)
# %num           (ruta del archivo que se genera cuando se usa la funcion SQTP, metodo = file)
#                / path to the file generated when using the SQTP function, method = file)
# %program       (nombre del programa / program name)

# Ejemplo de archivo pg / Example of a pg file:
# ---------------------------------------------
# Program  hex filename
# Driver   Alguno de los drivers definidos abajo / One of the drivers defined below
# Device   Alguno de los microcontroladores definidos para el driver / One of the microcontrollers defined for the driver
# Params   Datos que se adjuntan a la linea de comando (Velocidad del oscilador o tension de alimentacion, ver el manual del programa lanzado)
#          / Data attached to the command line (Oscillator speed or supply voltage, see the launched program's manual)
# SQTP_Dir Posicion inicial donde la numeracion SQTP va (en hexadecimal) / Initial position for the SQTP numbering (in hexadecimal)
# SQTP_Len Tamaño maximo para la numeracion SQTP (en bytes) / Maximum size for the SQTP numbering (in bytes)


[Default]
defaultprogdir = ./hexfiles
defaultsqtpdir = ./sqtpfiles

[flashmagic]
com_method = serial
SQTP_method = inject
path = C:/Program Files (x86)/Flash Magic PS/FMPS.EXE
Devices = LPC11E68,LPC4337
linea_comando = "%path" device(%device,%params) COM(%portn,115200) ERASE(DEVICE, PROTECTISP) HEXFILE("%hex", NOCHECKSUMS, NOFILL, PROTECTISP)
returncode_ok = OK
returncode_bad = FAIL

[IPECMD]
com_method = pickit5
path = '/opt/microchip/mplabx/v6.30/sys/java/zulu8.86.0.25-ca-fx-jre8.0.452-linux_x64/bin/java' '-jar' '/opt/microchip/mplabx/v6.30/mplab_platform/mplab_ipe/ipecmd.jar'
#windows path = "C:/progra~1/Microchip/MPLABX/v6.30/mplab_platform/mplab_ipe/ipecmd.exe"
Devices = PIC16F1825,PIC16F1829
linea_comando = %path -M -P%device -TS%port -F%hex -W%params
returncode_ok = Program Succeeded
returncode_bad = Operation Failed

[IPECMD_SQTP]
com_method = pickit5
SQTP_method = file
path = '/opt/microchip/mplabx/v6.30/sys/java/zulu8.86.0.25-ca-fx-jre8.0.452-linux_x64/bin/java' '-jar' '/opt/microchip/mplabx/v6.30/mplab_platform/mplab_ipe/ipecmd.jar'
#windows path = "C:/progra~1/Microchip/MPLABX/v6.30/mplab_platform/mplab_ipe/ipecmd.exe"
Devices = PIC18F4685
linea_comando = %path -M -P%device -TS%port -F"%hex" -W%params -S"%num"
returncode_ok = Program Succeeded
returncode_bad = Operation Failed



# Descripcion de los parametros / Parameter Descriptions:
# =========================================================
# [Nombre del Driver] / [Driver Name]
#
# com_method = Hardware de programacion (Actualmente serial o pickit5, para otro nuevo es necesario modificar la libreria omni_driver.py)
#            / Programming hardware (Currently serial or pickit5. To add a new one, omni_driver.py must be modified)
#
# SQTP_method = inject / file (Para otro nuevo es necesario modificar la libreria omni_firmware.py)
#             / inject / file (To add a new one, omni_firmware.py must be modified)
#
# path = ruta del ejecutable (debe ser del tipo linea de comandos)
#      / Path to the executable (must be a CLI / command-line tool)
#
# micros = Microcontroladores aceptados para este driver
#        / Microcontrollers supported by this driver
#
# linea_comando = Aqui la construccion de la linea de comando, usando los comodines a continuacion mostrados
#               / Command line construction, using the placeholders shown below
#
# returncode_ok = el numero que devuelve el programa cuando todo va bien o un texto inequivoco. (El texto debe ser en mayusculas)
#               / The number returned by the program on success, or an unambiguous string. (The text must be in UPPERCASE)
#
# returncode_bad = el numero que devuelve el programa cuando falla la programacion o un texto inequivoco. (forzar algun error para obtener un codigo o texto)
#                / The number returned by the program on failure, or an unambiguous string. (Force an error to get the code or text)

# Para añadir otro metodo de programación aqui aparece la descripcion de las variables.
# Variable descriptions for adding another programming method:
# ----------------------------------------------------------------------
# %path          (ruta del programa / program path)
# %device        (micro que aparecera en el archivo pg / microcontroller that will appear in the pg file)
# %params        (datos que aparecera en el archivo pg / data that will appear in the pg file)
# %port          (puerto que se elige en el GUI, nombre completo / port selected in the GUI, full name)
# %portn         (puerto que se elige en el GUI, solo numero / port selected in the GUI, number only)
# %hex           (ruta del hex que aparece en el archivo pg, o del result.hex que se genera cuando se usa la funcion SQTP, metodo = inject)
#                / path to the hex file in the pg file, or the result.hex generated when using the SQTP function, method = inject)
# %num           (ruta del archivo que se genera cuando se usa la funcion SQTP, metodo = file)
#                / path to the file generated when using the SQTP function, method = file)
# %program       (nombre del programa / program name)

# Ejemplo de archivo pg / Example of a pg file:
# ---------------------------------------------
# Program  hex filename
# Driver   Alguno de los drivers definidos abajo / One of the drivers defined below
# Device   Alguno de los microcontroladores definidos para el driver / One of the microcontrollers defined for the driver
# Params   Datos que se adjuntan a la linea de comando (Velocidad del oscilador o tension de alimentacion, ver el manual del programa lanzado)
#          / Data attached to the command line (Oscillator speed or supply voltage, see the launched program's manual)
# SQTP_Dir Posicion inicial donde la numeracion SQTP va (en hexadecimal) / Initial position for the SQTP numbering (in hexadecimal)
# SQTP_Len Tamaño maximo para la numeracion SQTP (en bytes) / Maximum size for the SQTP numbering (in bytes)
