# Para añadir otro metodo de programación aqui aparece la descripcion de las variables.
# %path (ruta del programa)
# %device (micro que aparecera en el archivo pg)
# %params (datos que aparecera en el archivo pg)
# %port (puerto que se elige en el GUI, nombre completo)
# %portn (puerto que se elige en el GUI, solo numero)
# %baudrate (baudrate)
# %hex (ruta del hex que aparece en el archivo pg, o del result.hex que se genera cuando se usa la funcion SQTP)

[Default]
defaultprogdir = ./hexprograms/
defaultsqtpdir = ./hexprograms/
debug = 1

[flashmagic]
driver = flashmagic
path = C:/Program Files (x86)/Flash Magic PS/FMPS.EXE
micros = LPC11E68,LPC4337
baudrate = 115200
linea_comando = "%path" device(%device,%params) COM(%portn,%baudrate) ERASE(DEVICE, PROTECTISP) HEXFILE(%hex, NOCHECKSUMS, NOFILL, PROTECTISP)

[IPECMD]
driver = pickit5
#path = /opt/microchip/mplabx/v6.30/sys/java/zulu8.86.0.25-ca-fx-jre8.0.452-linux_x64/bin/java -jar /opt/microchip/mplabx/v6.30/mplab_platform/mplab_ipe/ipecmd.jar
path = /opt/microchip/mplabx/v6.30/mplab_platform/mplab_ipe/ipecmd.sh
micros = PIC16F690,PIC16F1825,PIC16F1829,PIC18F4685
linea_comando = "%path" -P%device -TS%port -M -F%hex -W%params
